<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>GatherBuddy</RootNamespace>
    <AssemblyName>GatherBuddyAscended</AssemblyName>
    <Version>1.1.0.0</Version>
    <Company>Jack Luxear</Company>
    <Product>GatherBuddy Ascended</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Deterministic>true</Deterministic>
    <OutputType>Library</OutputType>
    <WarningLevel>4</WarningLevel>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <CopyLocalLockfileAssemblies>true</CopyLocalLockfileAssemblies>
    <Configurations>Debug;Release</Configurations>
    <Platforms>x64</Platforms>
    <Name>GatherBuddy Ascended</Name>
    <Author>Jack Luxear</Author>
    <Description>Adds commands to simplify gathering by finding nodes and fish and their locations via item name and a UI to keep track of special uptime and weather conditions. Also automatically gathers items based on these conditions using lists that you specify. Automated gathering requires vnavmesh.</Description>
    <Punchline>Simplify Gathering and Fishing to the extreme.</Punchline>
	</PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>GatherBuddy.Vulcan.Tests</_Parameter1>
    </AssemblyAttribute>
    <Compile Remove="AutoGather\GatheringTracker.cs" />
    <Compile Remove="Plugin\AutoGather.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="CustomInfo\IlvConvertTable.csv" />
    <None Remove="CustomInfo\mob_drop_overrides.json" />
    <None Remove="CustomInfo\world_locations.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CustomInfo\world_locations.json" />
    <EmbeddedResource Include="CustomInfo\mob_drop_overrides.json" />
    <None Remove="CustomInfo\node_offsets.json" />
    <EmbeddedResource Include="CustomInfo\node_offsets.json" />
    <None Remove="CustomInfo\honk-sound.wav" />
    <EmbeddedResource Include="CustomInfo\honk-sound.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSCore" Version="1.2.1.2" />
    <PackageReference Include="Dalamud.NET.Sdk" Version="15.0.0" />
    <PackageReference Include="LuminaSupplemental.Excel" Version="4.3.0" />
    <PackageReference Include="MessagePack" Version="3.1.3" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\GatherBuddy.GameData\GatherBuddy.GameData.csproj" />
	  <ProjectReference Include="..\GatherBuddy.Models\GatherBuddy.Models.csproj" />
	  <ProjectReference Include="..\ElliLib\ElliLib.csproj" />
	  <ProjectReference Include="..\ElliCon\ElliCon.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="AutoGather\Tasks\" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="CustomInfo\IlvConvertTable.csv" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="CustomInfo\fish_records.json" />
	</ItemGroup>


</Project>
