using System;
using System.Linq;
using System.Numerics;
using Dalamud.Bindings.ImGui;
using Dalamud.Interface.Colors;
using ElliLib.Raii;
using ElliLib.Widgets;
using FFXIVClientStructs.FFXIV.Client.Game;
using GatherBuddy.Config;
using GatherBuddy.Crafting;
using GatherBuddy.Plugin;
using ImRaii = ElliLib.Raii.ImRaii;

namespace GatherBuddy.Gui;

public partial class VulcanWindow
{
    private void DrawSettingsTab()
    {
        IDisposable tabItem;
        bool tabOpen;

        if (GatherBuddy.ControllerSupport != null)
        {
            var handle = GatherBuddy.ControllerSupport.TabNavigation.TabItem("Settings##settingsTab", 6, 9);
            tabItem = handle;
            tabOpen = handle;
        }
        else
        {
            var handle = ImRaii.TabItem("Settings##settingsTab");
            tabItem = handle;
            tabOpen = handle.Success;
        }

        using (tabItem)
        {
            if (!tabOpen)
                return;

            var coordinator = GatherBuddy.RaphaelSolveCoordinator;
            var raphaelConfig = GatherBuddy.Config.RaphaelSolverConfig;

            var currentMode = raphaelConfig.SolverMode;
            var modeNames = new[] { "Pure Raphael", "Standard Solver", "Progress Only", "Donatello" };
            var safeModeIndex = Math.Clamp((int)currentMode, 0, modeNames.Length - 1);
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(150f));
            if (ImGui.BeginCombo("Solver Mode###SolverMode", modeNames[safeModeIndex]))
            {
                if (ImGui.Selectable("Pure Raphael", currentMode == VulcanSolverMode.PureRaphael))
                {
                    raphaelConfig.SolverMode = VulcanSolverMode.PureRaphael;
                    GatherBuddy.Config.Save();
                    CraftingGameInterop.ReloadSolvers();
                }
                if (ImGui.IsItemHovered())
                {
                    ImGui.BeginTooltip();
                    ImGui.TextUnformatted("Pure Raphael: Static rotations generated by Raphael solver");
                    ImGui.TextUnformatted("Consistent, optimal results");
                    ImGui.EndTooltip();
                }

                if (ImGui.Selectable("Standard Solver", currentMode == VulcanSolverMode.StandardSolver))
                {
                    raphaelConfig.SolverMode = VulcanSolverMode.StandardSolver;
                    GatherBuddy.Config.Save();
                    CraftingGameInterop.ReloadSolvers();
                }
                if (ImGui.IsItemHovered())
                {
                    ImGui.BeginTooltip();
                    ImGui.TextUnformatted("Standard Solver: Dynamic solver adapted from Artisan");
                    ImGui.TextUnformatted("Reacts to conditions, more flexible");
                    ImGui.EndTooltip();
                }
                if (ImGui.Selectable("Donatello", currentMode == VulcanSolverMode.Donatello))
                {
                    raphaelConfig.SolverMode = VulcanSolverMode.Donatello;
                    GatherBuddy.Config.Save();
                    CraftingGameInterop.ReloadSolvers();
                }
                if (ImGui.IsItemHovered())
                {
                    ImGui.BeginTooltip();
                    ImGui.TextUnformatted("Donatello: Raphael optimization with live-state replanning");
                    ImGui.TextUnformatted("Adopts only independently proven strict improvements");
                    ImGui.EndTooltip();
                }
                if (ImGui.Selectable("Progress Only", currentMode == VulcanSolverMode.ProgressOnly))
                {
                    raphaelConfig.SolverMode = VulcanSolverMode.ProgressOnly;
                    GatherBuddy.Config.Save();
                    CraftingGameInterop.ReloadSolvers();
                }
                if (ImGui.IsItemHovered())
                {
                    ImGui.BeginTooltip();
                    ImGui.TextUnformatted("Progress Only: Completes crafts without quality actions");
                    ImGui.TextUnformatted("Fastest execution, no quality output");
                    ImGui.EndTooltip();
                }
                ImGui.EndCombo();
            }

            var delay = GatherBuddy.Config.VulcanExecutionDelayMs;
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(150f));
            if (ImGui.SliderInt("Action Delay (ms)", ref delay, 0, 1000))
            {
                GatherBuddy.Config.VulcanExecutionDelayMs = Math.Clamp(delay, 0, 1000);
                GatherBuddy.Config.Save();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Delay in milliseconds between each crafting action (0 = instant, max 1000ms)");

            var ctxMenuEntries = GatherBuddy.Config.VulcanContextMenuEntries;
            if (ImGui.Checkbox("Context Menu Entries (Vs in context menus)", ref ctxMenuEntries))
            {
                GatherBuddy.Config.VulcanContextMenuEntries = ctxMenuEntries;
                GatherBuddy.Config.Save();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Show Vulcan-related entries (Open in Vulcan, Add to Crafting List, Add to Vendor Buy List) in the in-game right-click menu.");

            var showRecipeBrowserTooltips = GatherBuddy.Config.ShowRecipeBrowserTooltips;
            if (ImGui.Checkbox("Show Recipe Browser Item Tooltips", ref showRecipeBrowserTooltips))
            {
                GatherBuddy.Config.ShowRecipeBrowserTooltips = showRecipeBrowserTooltips;
                GatherBuddy.Config.Save();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Show the native item tooltip when hovering recipe results in the Recipes tab.");

            if (Widget.ModifiableKeySelector("Hotkey to Open Recipes Tab",
                    "Set a hotkey to open Vulcan directly to the Recipes tab.",
                    VulcanUiScaling.Scaled(220f),
                    GatherBuddy.Config.VulcanRecipesTabHotkey,
                    k => GatherBuddy.Config.VulcanRecipesTabHotkey = k,
                    Configuration.ValidKeys))
            {
                GatherBuddy.Config.Save();
            }

            DrawVulcanRepairConfig();

            DrawVulcanMateriaConfig();

            DrawVulcanRetainerBellConfig();

            ImGui.Spacing();
            ImGui.Separator();
            ImGui.Spacing();

            ImGui.Text("Raphael / Donatello Solver");
            ImGui.Separator();
            ImGui.Spacing();

            ImGui.BeginGroup();
            ImGui.Text("  Max Concurrent: ");
            ImGui.SameLine();
            var maxConcurrent = raphaelConfig.MaxConcurrentRaphaelProcesses;
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(100f));
            if (ImGui.InputInt("###MaxConcurrent", ref maxConcurrent, 1, 1))
            {
                raphaelConfig.MaxConcurrentRaphaelProcesses = Math.Max(1, maxConcurrent);
                GatherBuddy.Config.Save();
            }

            ImGui.Text("  Solve Timeout (minutes): ");
            ImGui.SameLine();
            var timeoutMinutes = raphaelConfig.RaphaelTimeoutMinutes;
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(100f));
            if (ImGui.InputInt("###RaphaelTimeout", ref timeoutMinutes, 1, 1))
            {
                raphaelConfig.RaphaelTimeoutMinutes = Math.Max(1, Math.Min(60, timeoutMinutes));
                GatherBuddy.Config.Save();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Timeout in minutes per Raphael solve. If exceeded, the solution is marked as failed and the craft will be skipped.");

            ImGui.Text("  Cache Max Age (days): ");
            ImGui.SameLine();
            var maxAgeDays = raphaelConfig.SolutionCacheMaxAgeDays;
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(100f));
            if (ImGui.InputInt("###CacheMaxAge", ref maxAgeDays, 1, 10))
            {
                raphaelConfig.SolutionCacheMaxAgeDays = Math.Max(1, Math.Min(365, maxAgeDays));
                GatherBuddy.Config.Save();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Solutions older than this many days are discarded on plugin load.");

            ImGui.Spacing();
            var backloadProgress = raphaelConfig.RaphaelBackloadProgress;
            if (ImGui.Checkbox("  Backload Progress###RaphaelBackloadProgress", ref backloadProgress))
            {
                raphaelConfig.RaphaelBackloadProgress = backloadProgress;
                GatherBuddy.Config.Save();
                coordinator.Clear();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Only use progress-increasing actions at the end of the rotation.\nMay decrease achievable quality. Disable for maximum quality output.\nChanging this clears the solution cache.");

            var allowSpecialist = raphaelConfig.RaphaelAllowSpecialistActions;
            if (ImGui.Checkbox("  Allow Specialist Actions###RaphaelAllowSpecialist", ref allowSpecialist))
            {
                raphaelConfig.RaphaelAllowSpecialistActions = allowSpecialist;
                GatherBuddy.Config.Save();
                coordinator.Clear();
            }
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("When disabled (default), Raphael generates non-specialist rotations even if you are a specialist.\nEnable only if you want Raphael to use specialist actions.\nChanging this clears the solution cache.");

            var activeColor = coordinator.ActiveSolves > 0 ? ImGuiColors.HealerGreen : ImGuiColors.DalamudGrey;
            ImGui.TextColored(activeColor, $"  Active Solves: {coordinator.ActiveSolves}/{raphaelConfig.MaxConcurrentRaphaelProcesses}");

            var pendingColor = coordinator.PendingSolves > 0 ? ImGuiColors.DalamudOrange : ImGuiColors.DalamudGrey;
            ImGui.TextColored(pendingColor, $"  Pending: {coordinator.PendingSolves}");

            var cachedColor = coordinator.CachedSolutionCount > 0 ? ImGuiColors.HealerGreen : ImGuiColors.DalamudGrey;
            ImGui.TextColored(cachedColor, $"  Cached Solutions: {coordinator.CachedSolutionCount}");

            if (ImGui.Button("Clear Cache", VulcanUiScaling.Scaled(150f, 0f)))
            {
                coordinator.Clear();
            }
            ImGui.EndGroup();
        }
    }

    private void DrawVulcanRepairConfig()
    {
        var config = GatherBuddy.Config.VulcanRepairConfig;

        var enabled = config.Enabled;
        if (ImGui.Checkbox("Enable Repair", ref enabled))
        {
            config.Enabled = enabled;
            GatherBuddy.Config.Save();
        }
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip("Automatically repair equipment between crafts when needed");

        var threshold = config.RepairThreshold;
        ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(150f));
        if (ImGui.SliderInt("Repair Threshold (%)", ref threshold, 0, 99))
        {
            config.RepairThreshold = threshold;
            GatherBuddy.Config.Save();
        }
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip("Repair when minimum equipment condition drops below this percentage");

        var prioritizeNPC = config.PrioritizeNPCRepair;
        if (ImGui.Checkbox("Prioritize NPC Repair", ref prioritizeNPC))
        {
            config.PrioritizeNPCRepair = prioritizeNPC;
            GatherBuddy.Config.Save();
        }
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip("Use NPC repair if available and you have enough gil, otherwise use self-repair");
        
        if (config.PrioritizeNPCRepair)
        {
            ImGui.Spacing();
            ImGui.Text("Preferred Repair NPC:");
            if (ImGui.IsItemHovered())
                ImGui.SetTooltip("Select a repair NPC to travel to when repair is needed");
            
            ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(300f));
            var currentNPC = config.PreferredRepairNPC;
            var displayText = currentNPC != null 
                ? $"{currentNPC.Name} ({GetTerritoryName(currentNPC.TerritoryType)})"
                : "Current Zone NPCs";
            
            if (ImGui.BeginCombo("##PreferredRepairNPC", displayText))
            {
                ImGui.SetNextItemWidth(VulcanUiScaling.Scaled(280f));
                ImGui.InputTextWithHint("##RepairNPCSearch", "Search NPCs...", ref _repairNPCSearchInput, 256);
                ImGui.Separator();
                
                if (ImGui.Selectable("Current Zone NPCs", currentNPC == null))
                {
                    config.PreferredRepairNPC = null;
                    config.PreferredRepairNPCDataId = 0;
                    GatherBuddy.Config.Save();
                }
                if (ImGui.IsItemHovered())
                    ImGui.SetTooltip("Use any repair NPC in the current zone");
                
                var repairNPCs = Crafting.RepairNPCHelper.RepairNPCs;
                if (repairNPCs.Count == 0)
                {
                    ImGui.TextDisabled("No repair NPCs loaded yet...");
                }
                else
                {
                    var searchLower = _repairNPCSearchInput.ToLowerInvariant();
                    var filteredNPCs = string.IsNullOrWhiteSpace(_repairNPCSearchInput)
                        ? repairNPCs
                        : repairNPCs.Where(npc => 
                            npc.Name.ToLowerInvariant().Contains(searchLower) ||
                            GetTerritoryName(npc.TerritoryType).ToLowerInvariant().Contains(searchLower)).ToList();
                    
                    if (filteredNPCs.Count == 0)
                    {
                        ImGui.TextDisabled("No NPCs match your search...");
                    }
                    else
                    {
                        foreach (var npc in filteredNPCs)
                        {
                            var territoryName = GetTerritoryName(npc.TerritoryType);
                            var npcLabel = $"{npc.Name} - {territoryName}";
                            
                            if (ImGui.Selectable(npcLabel, currentNPC?.DataId == npc.DataId))
                            {
                                config.PreferredRepairNPC = npc;
                                config.PreferredRepairNPCDataId = npc.DataId;
                                GatherBuddy.Config.Save();
                            }
                        }
                    }
                }
                
                ImGui.EndCombo();
            }
        }
    }
    
    private void DrawVulcanMateriaConfig()
    {
        var config = GatherBuddy.Config.VulcanMateriaConfig;

        var enabled = config.Enabled;
        if (ImGui.Checkbox("Enable Materia Extraction", ref enabled))
        {
            config.Enabled = enabled;
            GatherBuddy.Config.Save();
        }
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip("Automatically extract materia from fully spiritbonded equipment between crafts");
    }

    private void DrawVulcanRetainerBellConfig()
    {
        var config = GatherBuddy.Config.VulcanRetainerBellConfig;

        var autoNav = config.AutoNavigateToRetainerBell;
        if (ImGui.Checkbox("Auto-Navigate to Retainer Bell", ref autoNav))
        {
            config.AutoNavigateToRetainerBell = autoNav;
            GatherBuddy.Config.Save();
        }
        if (ImGui.IsItemHovered())
            ImGui.SetTooltip("Automatically navigate to the nearest retainer bell when starting retainer restock");
    }
}
