[project]
name = "ffxiv-re-python"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "anytree==2.13.0",
    "frida>=17.17.0",
    "pyghidra",
    "pyyaml==6.0.3",
]

[tool.uv.sources]
pyghidra = { path = "/opt/ghidra/Ghidra/Features/PyGhidra/pypkg/dist/pyghidra-3.1.0-py3-none-any.whl" }
